In [67]:
import pandas as pd
from pandas import DataFrame, read_excel, merge
import matplotlib.pyplot as plt
import matplotlib.style
plt.style.use('fivethirtyeight')
import numpy as np
%matplotlib inline
from datetime import date
from dateutil.relativedelta import relativedelta
from qgrid import show_grid as sh 
import ipywidgets

In [68]:
pce = pd.read_csv(r"C:\Users\AEAData\Documents\PCE Data\PCE Statistical Table August 2018 Formatted.csv")

C:\Users\AEAData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (13,49) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [69]:
pce.head()

,Document No.,Line_No,Buy_from_Vendor_No.,Community_Name,Posting_Date,Month,Year,Posting_Description,Project_Code,Column1,...,Other_1_kWh_Generated,Other_1_kWh_Type,Other_2_kWh_Generated,Other_2_kWh_Type,Diesel_Efficiency,Dimension_6_Code,Created_By,Date_Created,Last_Modified,Last_Modified_By
0,NaN,10000,NORTSB,Nuiqsut,12/31/2009,12,2009,Subrec Grants-PCE,332380,332380,...,0,NaN,0,NaN,NaN,NaN,NaN,NaN,3/7/2011,LMACMILLAN
1,HISTPI030007,10000,ANIALPC,Aniak,4/3/2008,4,2008,Subrec Grants-PCE,331760,331760,...,0,NaN,0,NaN,12.768926,NaN,LMACMILLAN,4/3/2008,NaN,NaN
2,HISTPI030008,10000,BETHUC,Bethel,4/3/2008,4,2008,Subrec Grants-PCE,331800,331800,...,0,NaN,0,NaN,13.559435,NaN,LMACMILLAN,4/3/2008,NaN,NaN
3,HISTPI030008,20000,BETHUC,Bethel,4/3/2008,4,2008,Subrec Grants-PCE,331800,331800,...,0,NaN,0,NaN,13.559435,NaN,LMACMILLAN,4/3/2008,NaN,NaN
4,HISTPI030008,30000,BETHUC,Bethel,4/3/2008,4,2008,Subrec Grants-PCE,331800,331800,...,0,NaN,0,NaN,13.559435,NaN,LMACMILLAN,4/3/2008,NaN,NaN

In [70]:
intertie= pd.read_excel(r"C:\Users\AEAData\Desktop\Intertie dates with True-False.xlsx", sheet_name="Community lookup")

In [71]:
intertie_year=  pd.read_excel(r"C:\Users\AEAData\Desktop\Intertie dates with True-False.xlsx", sheet_name="Intertied communities")

In [72]:
intertie.columns

Index(['Community', 'gnis_feature_id', 'census_code', 'census_area__name',
       'census_area__gnis_feature_id', 'census_area__census_code',
       'census_area__county_code', 'alaska_native_regional_corporation__name',
       'latitude', 'longitude', 'aea_energy_region__name', 'Unnamed: 11',
       'Unnamed: 12', 'receiving_intertied_power'],
      dtype='object')

In [73]:
sh(intertie)

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': True, 'defauâ€¦

In [74]:
intertie.rename(columns = {'Community':'Community_Name' }, inplace=True)

In [75]:
intertie_year.rename(columns = {'Community':'Community_Name' }, inplace=True)

In [76]:
pce_test = pce.merge(intertie, on='Community_Name', how='left')

In [77]:
pce_test_1 =pce_test.merge(intertie_year, on='Community_Name', how='left')

In [78]:
pce_test_1.head()

,Document No.,Line_No,Buy_from_Vendor_No.,Community_Name,Posting_Date,Month,Year,Posting_Description,Project_Code,Column1,...,Year Community Intertied to source,Intertied after 2001,communities with intertied power,Notes,Utility,Funding source,Cost,Type,Distance (miles),Source
0,NaN,10000,NORTSB,Nuiqsut,12/31/2009,12,2009,Subrec Grants-PCE,332380,332380,...,NaN,NaN,NaN,NaN,North Slope Borough Power & Light,NaN,NaN,NaN,NaN,NaN
1,HISTPI030007,10000,ANIALPC,Aniak,4/3/2008,4,2008,Subrec Grants-PCE,331760,331760,...,NaN,NaN,NaN,NaN,Aniak Light & Power,NaN,NaN,NaN,NaN,NaN
2,HISTPI030008,10000,BETHUC,Bethel,4/3/2008,4,2008,Subrec Grants-PCE,331800,331800,...,NaN,NaN,Saint Michael,NaN,Alaska Village Electric Cooperative,NaN,NaN,NaN,NaN,NaN
3,HISTPI030008,20000,BETHUC,Bethel,4/3/2008,4,2008,Subrec Grants-PCE,331800,331800,...,NaN,NaN,Saint Michael,NaN,Alaska Village Electric Cooperative,NaN,NaN,NaN,NaN,NaN
4,HISTPI030008,30000,BETHUC,Bethel,4/3/2008,4,2008,Subrec Grants-PCE,331800,331800,...,NaN,NaN,Saint Michael,NaN,Alaska Village Electric Cooperative,NaN,NaN,NaN,NaN,NaN

In [79]:
pce_test_1.drop(['Document No.','Buy_from_Vendor_No.', 'Posting_Description', 'Source', 'Funding source', 'Intertie Unique ID', 'Unnamed: 11',
                'Unnamed: 12', 'Vendor_Invoice_No', 'Dimension_6_Code','Created_By', 'Date_Created', 'Last_Modified',
                'Last_Modified_By', 'census_code', 'census_area__name', 'census_area__gnis_feature_id', 'census_area__county_code',
                'PCE Community name', 'Pce ID', 'Cost', 'Type', 'Distance (miles)'], axis=1)

,Line_No,Community_Name,Posting_Date,Month,Year,Project_Code,Column1,Shortcut_Dimension_4_Code,Stage_Code,Amount,...,aea_energy_region__name,receiving_intertied_power,GNIS,Community Intertied,Source of electricity,Year Community Intertied to source,Intertied after 2001,communities with intertied power,Notes,Utility
0,10000,Nuiqsut,12/31/2009,12,2009,332380,332380,10225003,2,0.00,...,North Slope,No,1416680.0,No,Nuiqsut,NaN,NaN,NaN,NaN,North Slope Borough Power & Light
1,10000,Aniak,4/3/2008,4,2008,331760,331760,8225003,1,20443.57,...,Lower Yukon-Kuskokwim,No,1398286.0,No,Aniak,NaN,NaN,NaN,NaN,Aniak Light & Power
2,10000,Bethel,4/3/2008,4,2008,331800,331800,8225003,1,141411.46,...,Lower Yukon-Kuskokwim,No,1398908.0,Yes,Bethel,NaN,NaN,Saint Michael,NaN,Alaska Village Electric Cooperative
3,20000,Bethel,4/3/2008,4,2008,331800,331800,8225003,1,6223.72,...,Lower Yukon-Kuskokwim,No,1398908.0,Yes,Bethel,NaN,NaN,Saint Michael,NaN,Alaska Village Electric Cooperative
4,30000,Bethel,4/3/2008,4,2008,331800,331800,8225003,1,96.25,...,Lower Yukon-Kuskokwim,No,1398908.0,Yes,Bethel,NaN,NaN,Saint Michael,NaN,Alaska Village Electric Cooperative
5,40000,Bethel,4/3/2008,4,2008,331800,331800,8225003,1,0.08,...,Lower Yukon-Kuskokwim,No,1398908.0,Yes,Bethel,NaN,NaN,Saint Michael,NaN,Alaska Village Electric Cooperative
6,10000,Chilkat Valley,4/3/2008,4,2008,332660,332660,8225003,1,11334.80,...,Southeast,Yes,1421022.0,Yes,AP&T,2007-09-01 00:00:00,True,Dot Lake Village,NaN,Inside Passage Electric
7,10000,Tanana,4/3/2008,4,2008,332600,332600,8225003,1,9755.49,...,Yukon-Koyukuk/Upper Tanana,No,1410629.0,No,Tanana,NaN,NaN,NaN,NaN,Tanana Power Company Inc
8,10000,Angoon,4/3/2008,4,2008,332650,332650,8225003,1,17886.25,...,Southeast,No,1420113.0,No,Angoon,NaN,NaN,NaN,NaN,Inside Passage Electric
9,10000,Hoonah,4/3/2008,4,2008,332670,332670,8225003,1,45283.10,...,Southeast,No,1403488.0,No,Hoonah,NaN,NaN,NaN,NaN,Inside Passage Electric
10,20000,Hoonah,4/3/2008,4,2008,332670,332670,8225003,1,135.95,...,Southeast,No,1403488.0,No,Hoonah,NaN,NaN,NaN,NaN,Inside Passage Electric
11,30000,Hoonah,4/3/2008,4,2008,332670,332670,8225003,1,146.90,...,Southeast,No,1403488.0,No,Hoonah,NaN,NaN,NaN,NaN,Inside Passage Electric
12,10000,Kake,4/3/2008,4,2008,332680,332680,8225003,1,21851.38,...,Southeast,No,1422926.0,No,Kake,NaN,NaN,NaN,NaN,Inside Passage Electric
13,10000,Klukwan,4/3/2008,4,2008,332700,332700,8225003,1,4605.90,...,Southeast,Yes,1866956.0,Yes,AP&T,2000-01-01 00:00:00,False,Dot Lake,NaN,Inside Passage Electric
14,10000,Coffman Cove,4/3/2008,4,2008,331080,331080,8225003,1,9227.03,...,Southeast,Yes,1669437.0,Yes,POW grid,2011-10-01 00:00:00,True,Eyak,NaN,Alaska Power & Telephone Company
15,20000,Coffman Cove,4/3/2008,4,2008,331080,331080,8225003,1,0.01,...,Southeast,Yes,1669437.0,Yes,POW grid,2011-10-01 00:00:00,True,Eyak,NaN,Alaska Power & Telephone Company
16,10000,Coffman Cove,4/3/2008,4,2008,331080,331080,8225003,2,9702.41,...,Southeast,Yes,1669437.0,Yes,POW grid,2011-10-01 00:00:00,True,Eyak,NaN,Alaska Power & Telephone Company
17,20000,Coffman Cove,4/3/2008,4,2008,331080,331080,8225003,2,-0.04,...,Southeast,Yes,1669437.0,Yes,POW grid,2011-10-01 00:00:00,True,Eyak,NaN,Alaska Power & Telephone Company
18,10000,Craig,4/3/2008,4,2008,331090,331090,8225003,1,12015.44,...,Southeast,Yes,1421260.0,Yes,POW grid,NaN,NaN,South Naknek,NaN,Alaska Power & Telephone Company
19,20000,Craig,4/3/2008,4,2008,331090,331090,8225003,1,5.23,...,Southeast,Yes,1421260.0,Yes,POW grid,NaN,NaN,South Naknek,NaN,Alaska Power & Telephone Company
20,30000,Craig,4/3/2008,4,2008,331090,331090,8225003,1,-0.01,...,Southeast,Yes,1421260.0,Yes,POW grid,NaN,NaN,South Naknek,NaN,Alaska Power & Telephone Company
21,10000,Haines,4/3/2008,4,2008,331120,331120,8225003,1,20630.52,...,Southeast,Yes,1422400.0,Yes,Upper lynn canal,1998,False,Hydaburg,NaN,Alaska Power & Telephone Company
22,20000,Haines,4/3/2008,4,2008,331120,331120,8225003,1,16.16,...,Southeast,Yes,1422400.0,Yes,Upper lynn canal,1998,False,Hydaburg,NaN,Alaska Power & Telephone Company
23,30000,Haines,4/3/2008,4,2008,331120,331120,8225003,1,0.01,...,Southeast,Yes,1422400.0,Yes,Upper lynn canal,1998,False,Hydaburg,NaN,Alaska Power & Telephone Company
24,10000,Hollis,4/3/2008,4,2008,331140,331140,8225003,1,1297.53,...,Southeast,Yes,1866952.0,Yes,POW grid,2004-03-01 00:00:00,True,Aleknagik,NaN,Alaska Power & Telephone Company
25,20000,Hollis,4/3/2008,4,2008,331140,331140,8225003,1,9.34,...,Southeast,Yes,1866952.0,Yes,POW grid,2004-03-01 00:00:00,True,Aleknagik,NaN,Alaska Power & Telephone Company
26,10000,Hydaburg,4/3/2008,4,2008,331150,331150,8225003,1,2443.75,...,Southeast,Yes,1422709.0,Yes,POW grid,2006-01-01 00:00:00,True,Eagle Village,NaN,Alaska Power & Telephone Company
27,10000,Klawock,4/3/2008,4,2008,331155,331155,8225003,1,5504.67,...,Southeast,Yes,1423100.0,Yes,POW grid,1987,False,Nunapitchuk,NaN,Alaska Power & Telephone Company
28,10000,Naukati Bay,4/3/2008,4,2008,331170,331170,8225003,1,5162.70,...,Southeast,Yes,1866964.0,Yes,POW grid,2015-02-01 00:00:00,True,King Salmon,NaN,Alaska Power & Telephone Company
29,20000,Naukati Bay,4/3/2008,4,2008,331170,331170,8225003,1,0.01,...,Southeast,Yes,1866964.0,Yes,POW grid,2015-02-01 00:00:00,True,King Salmon,NaN,Alaska Power & Telephone Company
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68230,10000,Chitina,12/31/2014,12,2014,331890,331890,15225003,6,3259.99,...,Copper River/Chugach,No,1400337.0,No,Chitina,NaN,NaN,NaN,NaN,Chitina Electric Inc
68231,10000,Akiak,9/30/2014,9,2014,331030,331030,15225003,3,13303.94,...,Lower Yukon-Kuskokwim,No,1398012.0,No,Akiak,NaN,NaN,NaN,NaN,Akiak City Council
68232,10000,False Pass,12/31/2014,12,2014,331970,331970,15225003,6,2592.43,...,Aleutians,No,1418574.0,No,False Pass,NaN,NaN,NaN,NaN,"False Pass, City of"
68233,10000,Adak,11/30/2014,11,2014,331005,331005,15225003,5,27880.18,...,Aleutians,No,1418109.0,No,Adak,NaN,NaN,NaN,NaN,TDX Adak Generating LLC
68234,20000,Adak,11/30/2014,11,2014,331005,331005,15225003,5,-10539.01,...,Aleutians,No,1418109.0,No,Adak,NaN,NaN,NaN,NaN,TDX Adak Generating LLC
68235,10000,Kipnuk,12/31/2014,12,2014,332080,332080,15225003,6,15787.84,...,Lower Yukon-Kuskokwim,No,1404781.0,No,Kipnuk,NaN,NaN,NaN,NaN,Kipnuk Light Plant
68236,10000,Kwigillingok,12/31/2014,12,2014,332160,332160,15225003,6,17653.57,...,Lower Yukon-Kuskokwim,No,1405122.0,No,Kwigillingok,NaN,NaN,NaN,NaN,Kwigillingok Power Company
68237,10000,Manley Hot Springs,11/30/2014,11,2014,332200,332200,15225003,5,11085.71,...,Yukon-Koyukuk/Upper Tanana,No,1405922.0,No,Manley Hot Springs,NaN,NaN,NaN,NaN,TDX Manley Generating LLC
68238,10000,Nunam Iqua,11/30/2014,11,2014,332420,332420,15225003,5,4617.28,...,Lower Yukon-Kuskokwim,No,1409405.0,No,Nunam Iqua,NaN,NaN,NaN,NaN,Nunam Iqua Electric Company
68239,20000,Nunam Iqua,11/30/2014,11,2014,332420,332420,15225003,5,2638.10,...,Lower Yukon-Kuskokwim,No,1409405.0,No,Nunam Iqua,NaN,NaN,NaN,NaN,Nunam Iqua Electric Company
68240,10000,Tuntutuliak,12/31/2014,12,2014,332720,332720,15225003,6,13173.22,...,Lower Yukon-Kuskokwim,No,1411324.0,No,Tuntutuliak,NaN,NaN,NaN,NaN,Tuntutuliak Community
68241,10000,Akiak,7/31/2014,7,2014,331030,331030,15225003,1,13864.76,...,Lower Yukon-Kuskokwim,No,1398012.0,No,Akiak,NaN,NaN,NaN,NaN,Akiak City Council
68242,10000,Golovin,12/31/2014,12,2014,332000,332000,15225003,6,10723.77,...,Bering Straits,No,1402760.0,No,Golovin,NaN,NaN,NaN,NaN,Golovin Power Utilities
68243,10000,King Cove,11/30/2014,11,2014,332070,332070,15225003,5,8065.82,...,Aleutians,No,1418792.0,No,King Cove,NaN,NaN,NaN,NaN,"King Cove, City of"
68244,10000,Koliganek,12/31/2014,12,2014,332110,332110,15225003,6,9883.47,...,Bristol Bay,No,1404914.0,No,Koliganek,NaN,NaN,NaN,NaN,New Koliganek Village Council
68245,10000,Tenakee Springs,12/31/2014,12,2014,332630,332630,15225003,6,8412.19,...,Southeast,No,1415210.0,No,Tenakee Springs,NaN,NaN,NaN,NaN,"Tenakee Springs, City of"
68246,10000,Angoon,1/31/2015,1,2015,332650,332650,15225003,7,29728.32,...,Southeast,No,1420113.0,No,Angoon,NaN,NaN,NaN,NaN,Inside Passage Electric
68247,10000,Chilkat Valley,1/31/2015,1,2015,332660,332660,15225003,7,18412.64,...,Southeast,Yes,1421022.0,Yes,AP&T,2007-09-01 00:00:00,True,Dot Lake Village,NaN,Inside Passage Electric
68248,10000,Hoonah,1/31/2015,1,2015,332670,332670,15225003,7,69778.06,...,Southeast,No,1403488.0,No,Hoonah,NaN,NaN,NaN,NaN,Inside Passage Electric
68249,10000,Kake,1/31/2015,1,2015,332680,332680,15225003,7,38422.31,...,Southeast,No,1422926.0,No,Kake,NaN,NaN,NaN,NaN,Inside Passage Electric
68250,10000,Klukwan,1/31/2015,1,2015,332700,332700,15225003,7,8314.23,...,Southeast,Yes,1866956.0,Yes,AP&T,2000-01-01 00:00:00,False,Dot Lake,NaN,Inside Passage Electric
68251,10000,Angoon,2/28/2015,2,2015,332650,332650,15225003,8,28413.57,...,Southeast,No,1420113.0,No,Angoon,NaN,NaN,NaN,NaN,Inside Passage Electric
68252,10000,Chilkat Valley,2/28/2015,2,2015,332660,332660,15225003,8,17249.18,...,Southeast,Yes,1421022.0,Yes,AP&T,2007-09-01 00:00:00,True,Dot Lake Village,NaN,Inside Passage Electric
68253,10000,Hoonah,2/28/2015,2,2015,332670,332670,15225003,8,69085.21,...,Southeast,No,1403488.0,No,Hoonah,NaN,NaN,NaN,NaN,Inside Passage Electric
68254,10000,Kake,2/28/2015,2,2015,332680,332680,15225003,8,35501.95,...,Southeast,No,1422926.0,No,Kake,NaN,NaN,NaN,NaN,Inside Passage Electric
68255,10000,Klukwan,2/28/2015,2,2015,332700,332700,15225003,8,7937.97,...,Southeast,Yes,1866956.0,Yes,AP&T,2000-01-01 00:00:00,False,Dot Lake,NaN,Inside Passage Electric
68256,10000,Buckland,1/31/2015,1,2015,331820,331820,15225003,7,11375.81,...,Northwest Arctic,No,1412684.0,No,Buckland,NaN,NaN,NaN,NaN,"Buckland, City of"
68257,10000,Kotzebue,1/31/2015,1,2015,332130,332130,15225003,7,109351.37,...,Northwest Arctic,No,1413378.0,No,Kotzebue,NaN,NaN,NaN,NaN,Kotzebue Electric Association
68258,20000,Kotzebue,1/31/2015,1,2015,332130,332130,15225003,7,4478.72,...,Northwest Arctic,No,1413378.0,No,Kotzebue,NaN,NaN,NaN,NaN,Kotzebue Electric Association
68259,30000,Kotzebue,1/31/2015,1,2015,332130,332130,15225003,7,39.21,...,Northwest Arctic,No,1413378.0,No,Kotzebue,NaN,NaN,NaN,NaN,Kotzebue Electric Association

In [80]:
pce = pce_test_1.copy()

In [81]:
pce.shape

(68260, 85)

In [82]:
pce.columns

Index(['Document No.', 'Line_No', 'Buy_from_Vendor_No.', 'Community_Name',
       'Posting_Date', 'Month', 'Year', 'Posting_Description', 'Project_Code',
       'Column1', 'Shortcut_Dimension_4_Code', 'Stage_Code', 'Amount',
       'Vendor_Invoice_No', 'Document_Date', 'Actual_Rate', 'Pro_Rata_Rate',
       'Check', 'Residential_Rate', 'PCE_Eligible_Residential_kWh',
       'PCE_Eligible_Commercial__kWh', 'PCE_Eligible_Community_kWh',
       'PCE_Eligible_kWh_Total', 'Rate_ID', 'Purchased_From',
       'Powerhouse_Consumption_kWh', 'Peak_Consumption_kW',
       'Residential_Sold_To', 'Commercial_Sold_To', 'Com_Facil_Sold_To',
       'Govt_Facil_Sold_To', 'Unbilled_Sold_To',
       'Most_Recent_Fuel_Purch_Price', 'Fuel_Used_Gallons',
       'Non_Fuel_Expenses', 'Fuel_Cost', 'Total_kWh_Purchased',
       'Residential_Customers', 'Commercial_Customers', 'Com_Facil_Customers',
       'Govt_Facil_Customers', 'Unbilled_Customers', 'Other_Customers',
       'Other_Customers_Description', 'Diesel_kWh_Generated',
       'Hydro_kWh_Generated', 'Other_1_kWh_Generated', 'Other_1_kWh_Type',
       'Other_2_kWh_Generated', 'Other_2_kWh_Type', 'Diesel_Efficiency',
       'Dimension_6_Code', 'Created_By', 'Date_Created', 'Last_Modified',
       'Last_Modified_By', 'gnis_feature_id', 'census_code',
       'census_area__name', 'census_area__gnis_feature_id',
       'census_area__census_code', 'census_area__county_code',
       'alaska_native_regional_corporation__name', 'latitude', 'longitude',
       'aea_energy_region__name', 'Unnamed: 11', 'Unnamed: 12',
       'receiving_intertied_power', 'Intertie Unique ID', 'GNIS',
       'PCE Community name', 'Pce ID', 'Community Intertied',
       'Source of electricity', 'Year Community Intertied to source',
       'Intertied after 2001', 'communities with intertied power', 'Notes',
       'Utility', 'Funding source', 'Cost', 'Type', 'Distance (miles)',
       'Source'],
      dtype='object')

In [83]:
#drop those values to avoid skew
pce.drop(pce[pce.Shortcut_Dimension_4_Code ==0].index, inplace=True)

In [84]:
#checking work 
pce.query("Shortcut_Dimension_4_Code == 0").shape

(0, 85)

In [85]:
# drop month and year on imported .csv
pce = pce.drop(['Month', 'Year'], axis=1)

In [86]:
# create fiscal year offset variable
fiscal_month_offset = 6

In [87]:
# make a copy of the df
pce_1=pce.copy()

In [88]:
# split fiscal year from dimension code and add to 2000
pce_1['Fiscal_Year']= 2000 + np.floor_divide(pce_1['Shortcut_Dimension_4_Code'],1000000)

In [89]:
# Create Fiscal Date column 
pce_1['Fiscal_Date'] = pce_1.apply(lambda row: date(row['Fiscal_Year'], row['Stage_Code'], 1), axis=1)

In [90]:
# subtract fiscal date from fiscal offset and create a new column
pce_1['Calendar_Date'] = pce_1['Fiscal_Date'] - relativedelta(months=fiscal_month_offset)
pce_1['Calendar_Date']= pd.to_datetime(pce_1['Calendar_Date'])

In [91]:
# strip month and year from datetime and convert to a string
pce_1['Month']= pce_1['Calendar_Date'].dt.strftime('%m')
pce_1['Year']= pce_1['Calendar_Date'].dt.strftime('%Y')

In [92]:
# convert Month and Year String to integer
pce_1['Month'] = pce_1.Month.astype(int)
pce_1['Year'] = pce_1.Year.astype(int)

In [93]:
pce=pce_1.copy()

In [94]:
pce.head()

,Document No.,Line_No,Buy_from_Vendor_No.,Community_Name,Posting_Date,Posting_Description,Project_Code,Column1,Shortcut_Dimension_4_Code,Stage_Code,...,Funding source,Cost,Type,Distance (miles),Source,Fiscal_Year,Fiscal_Date,Calendar_Date,Month,Year
0,NaN,10000,NORTSB,Nuiqsut,12/31/2009,Subrec Grants-PCE,332380,332380,10225003,2,...,NaN,NaN,NaN,NaN,NaN,2010,2010-02-01,2009-08-01,8,2009
1,HISTPI030007,10000,ANIALPC,Aniak,4/3/2008,Subrec Grants-PCE,331760,331760,8225003,1,...,NaN,NaN,NaN,NaN,NaN,2008,2008-01-01,2007-07-01,7,2007
2,HISTPI030008,10000,BETHUC,Bethel,4/3/2008,Subrec Grants-PCE,331800,331800,8225003,1,...,NaN,NaN,NaN,NaN,NaN,2008,2008-01-01,2007-07-01,7,2007
3,HISTPI030008,20000,BETHUC,Bethel,4/3/2008,Subrec Grants-PCE,331800,331800,8225003,1,...,NaN,NaN,NaN,NaN,NaN,2008,2008-01-01,2007-07-01,7,2007
4,HISTPI030008,30000,BETHUC,Bethel,4/3/2008,Subrec Grants-PCE,331800,331800,8225003,1,...,NaN,NaN,NaN,NaN,NaN,2008,2008-01-01,2007-07-01,7,2007

In [95]:
#Sum amount from line no 10000, 20000, 30000, 40000 into 10000 and creat new column
grouped_pce_amount=pce.groupby(['Community_Name','Month','Year'])[["Amount"]].sum()
grouped_pce_amount = grouped_pce_amount.reset_index()
grouped_pce_amount = grouped_pce_amount.rename(columns={'Amount':'Amount_Combined'})
pce_2 = pd.merge(pce, grouped_pce_amount, how='left', 
                          left_on=['Community_Name','Month', 'Year'], right_on=['Community_Name', 'Month', 'Year'])

In [96]:
pce_2.shape

(68256, 89)

In [97]:
#remove line no 20000, 30000, 40000 values as they are redundant now
pce_3=pce_2.drop(pce_2[pce_2.Line_No == 20000].index)
pce_4=pce_3.drop(pce_3[pce_3.Line_No == 30000].index)
pce_5=pce_4.drop(pce_4[pce_4.Line_No == 40000].index)

pce=pce_5.copy()
pce.shape

(35135, 89)

In [98]:
#Calculations for line loss, new line loss columns added to df
pce['Total_Sold']= pce.Residential_Sold_To + pce.Commercial_Sold_To + pce.Com_Facil_Sold_To + pce.Govt_Facil_Sold_To + pce.Unbilled_Sold_To
pce['Total_Generated']= pce.Diesel_kWh_Generated + pce.Hydro_kWh_Generated + pce.Other_1_kWh_Generated  + pce.Other_2_kWh_Generated + pce.Total_kWh_Purchased
pce['Total_Adjusted_Generation']= pce.Total_Generated - pce.Powerhouse_Consumption_kWh

pce['Line_Efficiency']= round(pce.Total_Sold / pce.Total_Adjusted_Generation,4)
pce['Line_Loss']= 1- pce.Line_Efficiency

line_loss = ['Residential_Rate','Year_Intertied','Community_Name','Calendar_Date', 'Total_Sold', 'Total_Generated', 'Total_Adjusted_Generation', 
             'Line_Loss', 'receiving_intertied_power']

In [99]:
pce.shape

(35135, 94)

In [100]:
pce.drop(['Document No.','Buy_from_Vendor_No.', 'Posting_Description', 'Source', 'Funding source', 'Intertie Unique ID', 'Unnamed: 11',
                'Unnamed: 12', 'Vendor_Invoice_No', 'Dimension_6_Code','Created_By', 'Date_Created', 'Last_Modified',
                'Last_Modified_By', 'census_code', 'census_area__name', 'census_area__gnis_feature_id', 'census_area__county_code',
                'PCE Community name', 'Pce ID', 'Cost', 'Type', 'Distance (miles)', 'Line_No', 'Column1', 'Document_Date',
                 'Check','Notes', 'communities with intertied power'], axis=1)

,Community_Name,Posting_Date,Project_Code,Shortcut_Dimension_4_Code,Stage_Code,Amount,Actual_Rate,Pro_Rata_Rate,Residential_Rate,PCE_Eligible_Residential_kWh,...,Fiscal_Date,Calendar_Date,Month,Year,Amount_Combined,Total_Sold,Total_Generated,Total_Adjusted_Generation,Line_Efficiency,Line_Loss
0,Nuiqsut,12/31/2009,332380,10225003,2,0.00,0.0000,0.0000,0.1145,39751,...,2010-02-01,2009-08-01,8,2009,1036.68,0,0,0,NaN,NaN
1,Aniak,4/3/2008,331760,8225003,1,20443.57,0.3765,0.3765,0.0000,51383,...,2008-01-01,2007-07-01,7,2007,20443.57,150461,173900,171390,0.877900,0.122100
2,Bethel,4/3/2008,331800,8225003,1,141411.46,0.2412,0.2412,0.3922,569179,...,2008-01-01,2007-07-01,7,2007,147731.51,2943211,3267200,3209600,0.917000,0.083000
6,Chilkat Valley,4/3/2008,332660,8225003,1,11334.80,0.2973,0.2938,0.4177,38491,...,2008-01-01,2007-07-01,7,2007,11334.80,88931,141000,135614,0.655800,0.344200
7,Tanana,4/3/2008,332600,8225003,1,9755.49,0.3765,0.3765,0.5693,20993,...,2008-01-01,2007-07-01,7,2007,9755.49,69592,80220,77130,0.902300,0.097700
8,Angoon,4/3/2008,332650,8225003,1,17886.25,0.2973,0.2938,0.4177,50129,...,2008-01-01,2007-07-01,7,2007,17886.25,125485,147565,145018,0.865300,0.134700
9,Hoonah,4/3/2008,332670,8225003,1,45283.10,0.2973,0.2938,0.4177,120416,...,2008-01-01,2007-07-01,7,2007,45565.95,408286,460722,453047,0.901200,0.098800
12,Kake,4/3/2008,332680,8225003,1,21851.38,0.2973,0.2938,0.4177,64535,...,2008-01-01,2007-07-01,7,2007,21851.38,155140,184987,177787,0.872600,0.127400
13,Klukwan,4/3/2008,332700,8225003,1,4605.90,0.2973,0.2938,0.4177,13808,...,2008-01-01,2007-07-01,7,2007,4605.90,24579,0,0,inf,-inf
14,Coffman Cove,4/3/2008,331080,8225003,1,9227.03,0.2215,0.2215,0.3899,34211,...,2008-01-01,2007-07-01,7,2007,9227.04,74644,82715,82055,0.909700,0.090300
16,Coffman Cove,4/3/2008,331080,8225003,2,9702.41,0.2187,0.2187,0.3869,36560,...,2008-02-01,2007-08-01,8,2007,9702.37,84766,89226,88362,0.959300,0.040700
18,Craig,4/3/2008,331090,8225003,1,12015.44,0.0466,0.0466,0.1924,180492,...,2008-01-01,2007-07-01,7,2007,12020.66,960639,2259321,2242111,0.428500,0.571500
21,Haines,4/3/2008,331120,8225003,1,20630.52,0.0702,0.0702,0.2156,276575,...,2008-01-01,2007-07-01,7,2007,20646.69,973797,1115565,1092645,0.891200,0.108800
24,Hollis,4/3/2008,331140,8225003,1,1297.53,0.0466,0.0466,0.1924,27623,...,2008-01-01,2007-07-01,7,2007,1306.87,54932,0,0,inf,-inf
26,Hydaburg,4/3/2008,331150,8225003,1,2443.75,0.0466,0.0466,0.1924,46096,...,2008-01-01,2007-07-01,7,2007,2443.75,105809,0,0,inf,-inf
27,Klawock,4/3/2008,331155,8225003,1,5504.67,0.0466,0.0466,0.1924,98186,...,2008-01-01,2007-07-01,7,2007,5504.67,755051,0,0,inf,-inf
28,Naukati Bay,4/3/2008,331170,8225003,1,5162.70,0.3111,0.3111,0.4842,16595,...,2008-01-01,2007-07-01,7,2007,5162.71,33753,36919,35551,0.949400,0.050600
30,Naukati Bay,4/3/2008,331170,8225003,2,4887.10,0.2842,0.2842,0.4679,17196,...,2008-02-01,2007-08-01,8,2007,4887.14,34704,37606,36190,0.958900,0.041100
32,Skagway,4/3/2008,331190,8225003,1,15053.69,0.0702,0.0702,0.2156,154660,...,2008-01-01,2007-07-01,7,2007,15053.65,1383215,1476192,1471753,0.939800,0.060200
34,Thorne Bay,4/3/2008,331210,8225003,1,4174.66,0.0466,0.0466,0.1924,65087,...,2008-01-01,2007-07-01,7,2007,4174.67,256754,0,0,inf,-inf
36,Whale Pass,4/3/2008,331230,8225003,1,3727.15,0.3199,0.3199,0.5067,11453,...,2008-01-01,2007-07-01,7,2007,3743.81,33746,40320,39653,0.851000,0.149000
39,Whale Pass,4/3/2008,331230,8225003,2,3421.68,0.2678,0.2678,0.4496,12545,...,2008-02-01,2007-08-01,8,2007,3421.68,41011,43968,42582,0.963100,0.036900
40,Central,4/3/2008,331830,8225003,1,5785.47,0.3224,0.3224,0.5089,17231,...,2008-01-01,2007-07-01,7,2007,5785.44,32638,36279,34923,0.934600,0.065400
42,Manley Hot Springs,4/3/2008,332200,8225003,1,2908.00,0.3765,0.3351,0.6010,8648,...,2008-01-01,2007-07-01,7,2007,2794.64,16169,21360,19901,0.812500,0.187500
45,Port Alsworth,4/3/2008,332590,8225003,1,5521.39,0.3658,0.3658,0.6037,15094,...,2008-01-01,2007-07-01,7,2007,5521.25,53966,57835,57070,0.945600,0.054400
47,Unalakleet,4/3/2008,332850,8225003,1,19764.99,0.2167,0.2167,0.3368,69578,...,2008-01-01,2007-07-01,7,2007,19765.08,251129,266640,261106,0.961800,0.038200
49,Iliamna,4/3/2008,332050,8225003,1,1166.69,0.2413,0.2413,0.0000,0,...,2008-01-01,2007-07-01,7,2007,18141.95,209740,256300,242020,0.866600,0.133400
52,McGrath,4/3/2008,332220,8225003,1,1363.27,0.2967,0.2642,0.0000,0,...,2008-01-01,2007-07-01,7,2007,17365.59,184383,211200,199455,0.924400,0.075600
54,Chefornak,4/3/2008,332310,8225003,1,8748.65,0.2861,0.2861,0.0000,27144,...,2008-01-01,2007-07-01,7,2007,8748.65,56253,67038,65693,0.856300,0.143700
55,White Mountain,4/3/2008,332890,8225003,1,7667.80,0.3255,0.3255,0.6000,16186,...,2008-01-01,2007-07-01,7,2007,7667.82,39315,45300,43246,0.909100,0.090900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68221,Sleetmute,12/31/2014,332260,15225003,6,8084.72,0.8092,0.8092,1.1628,6127,...,2015-06-01,2014-12-01,12,2014,8084.72,19780,27350,26375,0.750000,0.250000
68222,Stony River,12/31/2014,332270,15225003,6,2111.20,0.8092,0.8092,1.1628,2609,...,2015-06-01,2014-12-01,12,2014,2111.20,8344,10057,9359,0.891500,0.108500
68223,Larsen Bay,12/31/2014,332170,15225003,6,809.18,0.0548,0.0548,0.4400,8606,...,2015-06-01,2014-12-01,12,2014,809.18,80775,96806,94338,0.856200,0.143800
68224,Yakutat,12/31/2014,332900,15225003,6,37931.74,0.3079,0.3079,0.5385,93776,...,2015-06-01,2014-12-01,12,2014,37893.37,401201,444687,434629,0.923100,0.076900
68226,Chitina,12/31/2014,331890,15225003,6,3259.99,0.3424,0.3424,0.6987,8262,...,2015-06-01,2014-12-01,12,2014,3259.99,34970,40607,36796,0.950400,0.049600
68227,Akiak,9/30/2014,331030,15225003,3,13303.94,0.4314,0.4314,0.6300,28720,...,2015-03-01,2014-09-01,9,2014,13303.94,88631,86684,84203,1.052600,-0.052600
68228,False Pass,12/31/2014,331970,15225003,6,2592.43,0.2718,0.2718,0.4200,6738,...,2015-06-01,2014-12-01,12,2014,2592.43,51357,61067,57969,0.885900,0.114100
68229,Adak,11/30/2014,331005,15225003,5,27880.18,0.8092,0.8092,1.5647,19003,...,2015-05-01,2014-11-01,11,2014,17341.17,103979,162956,162956,0.638100,0.361900
68231,Kipnuk,12/31/2014,332080,15225003,6,15787.84,0.2609,0.2609,0.4613,58810,...,2015-06-01,2014-12-01,12,2014,15787.84,158364,170472,168382,0.940500,0.059500
68232,Kwigillingok,12/31/2014,332160,15225003,6,17653.57,0.4014,0.4014,0.6100,35189,...,2015-06-01,2014-12-01,12,2014,17653.57,126789,132950,128452,0.987100,0.012900
68233,Manley Hot Springs,11/30/2014,332200,15225003,5,11085.71,0.7549,0.7549,0.9287,11383,...,2015-05-01,2014-11-01,11,2014,11085.71,29663,37415,36152,0.820500,0.179500
68234,Nunam Iqua,11/30/2014,332420,15225003,5,4617.28,0.3359,0.3359,0.5300,13746,...,2015-05-01,2014-11-01,11,2014,7255.38,82641,88327,86441,0.956000,0.044000
68236,Tuntutuliak,12/31/2014,332720,15225003,6,13173.22,0.3281,0.3281,0.6500,36610,...,2015-06-01,2014-12-01,12,2014,13173.22,90151,104935,101182,0.891000,0.109000
68237,Akiak,7/31/2014,331030,15225003,1,13864.76,0.4314,0.4314,0.6300,29096,...,2015-01-01,2014-07-01,7,2014,13864.76,93915,77700,75656,1.241300,-0.241300
68238,Golovin,12/31/2014,332000,15225003,6,10723.77,0.3362,0.3362,0.5600,19227,...,2015-06-01,2014-12-01,12,2014,10723.77,77116,78217,78217,0.985900,0.014100
68239,King Cove,11/30/2014,332070,15225003,5,8065.82,0.0631,0.0631,0.3000,62446,...,2015-05-01,2014-11-01,11,2014,8065.82,317012,386000,377262,0.840300,0.159700
68240,Koliganek,12/31/2014,332110,15225003,6,9883.47,0.3518,0.3518,0.5000,22404,...,2015-06-01,2014-12-01,12,2014,9883.47,61041,67800,65033,0.938600,0.061400
68241,Tenakee Springs,12/31/2014,332630,15225003,6,8412.19,0.4057,0.4057,0.7200,18088,...,2015-06-01,2014-12-01,12,2014,8412.19,30928,36657,35522,0.870700,0.129300
68242,Angoon,1/31/2015,332650,15225003,7,29728.32,0.3899,0.3899,0.6225,54460,...,2015-07-01,2015-01-01,1,2015,29728.32,144770,168282,161776,0.894900,0.105100
68243,Chilkat Valley,1/31/2015,332660,15225003,7,18412.64,0.3899,0.3899,0.6225,47122,...,2015-07-01,2015-01-01,1,2015,18412.64,104287,163140,154253,0.676100,0.323900
68244,Hoonah,1/31/2015,332670,15225003,7,69778.06,0.3899,0.3899,0.6225,123104,...,2015-07-01,2015-01-01,1,2015,69778.06,377677,417604,409701,0.921800,0.078200
68245,Kake,1/31/2015,332680,15225003,7,38422.31,0.3899,0.3899,0.6225,77257,...,2015-07-01,2015-01-01,1,2015,38422.31,192747,220955,213955,0.900900,0.099100
68246,Klukwan,1/31/2015,332700,15225003,7,8314.23,0.3899,0.3899,0.6225,14814,...,2015-07-01,2015-01-01,1,2015,8314.23,35540,0,0,inf,-inf
68247,Angoon,2/28/2015,332650,15225003,8,28413.57,0.3899,0.3899,0.6225,52279,...,2015-08-01,2015-02-01,2,2015,28413.57,140223,159846,154308,0.908700,0.091300
68248,Chilkat Valley,2/28/2015,332660,15225003,8,17249.18,0.3899,0.3899,0.6225,44144,...,2015-08-01,2015-02-01,2,2015,17249.18,98027,157380,152891,0.641200,0.358800
68249,Hoonah,2/28/2015,332670,15225003,8,69085.21,0.3899,0.3899,0.6225,121327,...,2015-08-01,2015-02-01,2,2015,69085.21,363081,395018,387856,0.936100,0.063900
68250,Kake,2/28/2015,332680,15225003,8,35501.95,0.3899,0.3899,0.6225,71889,...,2015-08-01,2015-02-01,2,2015,35501.95,178512,206657,200157,0.891900,0.108100
68251,Klukwan,2/28/2015,332700,15225003,8,7937.97,0.3899,0.3899,0.6225,13849,...,2015-08-01,2015-02-01,2,2015,7937.97,33872,0,0,inf,-inf
68252,Buckland,1/31/2015,331820,15225003,7,11375.81,0.2509,0.2509,0.4741,42693,...,2015-07-01,2015-01-01,1,2015,11375.81,159909,175636,172833,0.925200,0.074800
68253,Kotzebue,1/31/2015,332130,15225003,7,109351.37,0.2438,0.2438,0.4021,325242,...,2015-07-01,2015-01-01,1,2015,113869.30,1810611,1948708,1914185,0.945900,0.054100

In [101]:
pce.rename(columns={'Year Community Intertied to source': 'Year_Intertied'}, inplace=True)
pce

,Document No.,Line_No,Buy_from_Vendor_No.,Community_Name,Posting_Date,Posting_Description,Project_Code,Column1,Shortcut_Dimension_4_Code,Stage_Code,...,Fiscal_Date,Calendar_Date,Month,Year,Amount_Combined,Total_Sold,Total_Generated,Total_Adjusted_Generation,Line_Efficiency,Line_Loss
0,NaN,10000,NORTSB,Nuiqsut,12/31/2009,Subrec Grants-PCE,332380,332380,10225003,2,...,2010-02-01,2009-08-01,8,2009,1036.68,0,0,0,NaN,NaN
1,HISTPI030007,10000,ANIALPC,Aniak,4/3/2008,Subrec Grants-PCE,331760,331760,8225003,1,...,2008-01-01,2007-07-01,7,2007,20443.57,150461,173900,171390,0.877900,0.122100
2,HISTPI030008,10000,BETHUC,Bethel,4/3/2008,Subrec Grants-PCE,331800,331800,8225003,1,...,2008-01-01,2007-07-01,7,2007,147731.51,2943211,3267200,3209600,0.917000,0.083000
6,HISTPI030009,10000,INSIPEC,Chilkat Valley,4/3/2008,Subrec Grants-PCE,332660,332660,8225003,1,...,2008-01-01,2007-07-01,7,2007,11334.80,88931,141000,135614,0.655800,0.344200
7,HISTPI030010,10000,TANAPC,Tanana,4/3/2008,Subrec Grants-PCE,332600,332600,8225003,1,...,2008-01-01,2007-07-01,7,2007,9755.49,69592,80220,77130,0.902300,0.097700
8,HISTPI030011,10000,INSIPEC,Angoon,4/3/2008,Subrec Grants-PCE,332650,332650,8225003,1,...,2008-01-01,2007-07-01,7,2007,17886.25,125485,147565,145018,0.865300,0.134700
9,HISTPI030012,10000,INSIPEC,Hoonah,4/3/2008,Subrec Grants-PCE,332670,332670,8225003,1,...,2008-01-01,2007-07-01,7,2007,45565.95,408286,460722,453047,0.901200,0.098800
12,HISTPI030013,10000,INSIPEC,Kake,4/3/2008,Subrec Grants-PCE,332680,332680,8225003,1,...,2008-01-01,2007-07-01,7,2007,21851.38,155140,184987,177787,0.872600,0.127400
13,HISTPI030014,10000,INSIPEC,Klukwan,4/3/2008,Subrec Grants-PCE,332700,332700,8225003,1,...,2008-01-01,2007-07-01,7,2007,4605.90,24579,0,0,inf,-inf
14,HISTPI030015,10000,ALASPCA,Coffman Cove,4/3/2008,Subrec Grants-PCE,331080,331080,8225003,1,...,2008-01-01,2007-07-01,7,2007,9227.04,74644,82715,82055,0.909700,0.090300
16,HISTPI030016,10000,ALASPCA,Coffman Cove,4/3/2008,Subrec Grants-PCE,331080,331080,8225003,2,...,2008-02-01,2007-08-01,8,2007,9702.37,84766,89226,88362,0.959300,0.040700
18,HISTPI030017,10000,ALASPCA,Craig,4/3/2008,Subrec Grants-PCE,331090,331090,8225003,1,...,2008-01-01,2007-07-01,7,2007,12020.66,960639,2259321,2242111,0.428500,0.571500
21,HISTPI030018,10000,ALASPCA,Haines,4/3/2008,Subrec Grants-PCE,331120,331120,8225003,1,...,2008-01-01,2007-07-01,7,2007,20646.69,973797,1115565,1092645,0.891200,0.108800
24,HISTPI030019,10000,ALASPCA,Hollis,4/3/2008,Subrec Grants-PCE,331140,331140,8225003,1,...,2008-01-01,2007-07-01,7,2007,1306.87,54932,0,0,inf,-inf
26,HISTPI030020,10000,ALASPCA,Hydaburg,4/3/2008,Subrec Grants-PCE,331150,331150,8225003,1,...,2008-01-01,2007-07-01,7,2007,2443.75,105809,0,0,inf,-inf
27,HISTPI030021,10000,ALASPCA,Klawock,4/3/2008,Subrec Grants-PCE,331155,331155,8225003,1,...,2008-01-01,2007-07-01,7,2007,5504.67,755051,0,0,inf,-inf
28,HISTPI030022,10000,ALASPCA,Naukati Bay,4/3/2008,Subrec Grants-PCE,331170,331170,8225003,1,...,2008-01-01,2007-07-01,7,2007,5162.71,33753,36919,35551,0.949400,0.050600
30,HISTPI030023,10000,ALASPCA,Naukati Bay,4/3/2008,Subrec Grants-PCE,331170,331170,8225003,2,...,2008-02-01,2007-08-01,8,2007,4887.14,34704,37606,36190,0.958900,0.041100
32,HISTPI030024,10000,ALASPCA,Skagway,4/3/2008,Subrec Grants-PCE,331190,331190,8225003,1,...,2008-01-01,2007-07-01,7,2007,15053.65,1383215,1476192,1471753,0.939800,0.060200
34,HISTPI030025,10000,ALASPCA,Thorne Bay,4/3/2008,Subrec Grants-PCE,331210,331210,8225003,1,...,2008-01-01,2007-07-01,7,2007,4174.67,256754,0,0,inf,-inf
36,HISTPI030026,10000,ALASPCA,Whale Pass,4/3/2008,Subrec Grants-PCE,331230,331230,8225003,1,...,2008-01-01,2007-07-01,7,2007,3743.81,33746,40320,39653,0.851000,0.149000
39,HISTPI030027,10000,ALASPCA,Whale Pass,4/3/2008,Subrec Grants-PCE,331230,331230,8225003,2,...,2008-02-01,2007-08-01,8,2007,3421.68,41011,43968,42582,0.963100,0.036900
40,HISTPI030028,10000,CENTEI,Central,4/3/2008,Subrec Grants-PCE,331830,331830,8225003,1,...,2008-01-01,2007-07-01,7,2007,5785.44,32638,36279,34923,0.934600,0.065400
42,HISTPI030029,10000,MANLU,Manley Hot Springs,4/3/2008,Subrec Grants-PCE,332200,332200,8225003,1,...,2008-01-01,2007-07-01,7,2007,2794.64,16169,21360,19901,0.812500,0.187500
45,HISTPI030030,10000,TANAEC,Port Alsworth,4/3/2008,Subrec Grants-PCE,332590,332590,8225003,1,...,2008-01-01,2007-07-01,7,2007,5521.25,53966,57835,57070,0.945600,0.054400
47,HISTPI030031,10000,UNALVEC,Unalakleet,4/3/2008,Subrec Grants-PCE,332850,332850,8225003,1,...,2008-01-01,2007-07-01,7,2007,19765.08,251129,266640,261106,0.961800,0.038200
49,HISTPI030032,10000,ILIANNE,Iliamna,4/3/2008,Subrec Grants-PCE,332050,332050,8225003,1,...,2008-01-01,2007-07-01,7,2007,18141.95,209740,256300,242020,0.866600,0.133400
52,HISTPI030033,10000,MCGRLP,McGrath,4/3/2008,Subrec Grants-PCE,332220,332220,8225003,1,...,2008-01-01,2007-07-01,7,2007,17365.59,184383,211200,199455,0.924400,0.075600
54,HISTPI030034,10000,NATELP,Chefornak,4/3/2008,Subrec Grants-PCE,332310,332310,8225003,1,...,2008-01-01,2007-07-01,7,2007,8748.65,56253,67038,65693,0.856300,0.143700
55,HISTPI030035,10000,WHITMU,White Mountain,4/3/2008,Subrec Grants-PCE,332890,332890,8225003,1,...,2008-01-01,2007-07-01,7,2007,7667.82,39315,45300,43246,0.909100,0.090900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68221,PPI99424,10000,MIDDKEC,Sleetmute,12/31/2014,Subrec Grants-PCE,332260,332260,15225003,6,...,2015-06-01,2014-12-01,12,2014,8084.72,19780,27350,26375,0.750000,0.250000
68222,PPI99425,10000,MIDDKEC,Stony River,12/31/2014,Subrec Grants-PCE,332270,332270,15225003,6,...,2015-06-01,2014-12-01,12,2014,2111.20,8344,10057,9359,0.891500,0.108500
68223,PPI99426,10000,LARSBUC,Larsen Bay,12/31/2014,Subrec Grants-PCE,332170,332170,15225003,6,...,2015-06-01,2014-12-01,12,2014,809.18,80775,96806,94338,0.856200,0.143800
68224,PPI99440,10000,YAKUP,Yakutat,12/31/2014,Subrec Grants-PCE,332900,332900,15225003,6,...,2015-06-01,2014-12-01,12,2014,37893.37,401201,444687,434629,0.923100,0.076900
68226,PPI99441,10000,CHITE,Chitina,12/31/2014,Subrec Grants-PCE,331890,331890,15225003,6,...,2015-06-01,2014-12-01,12,2014,3259.99,34970,40607,36796,0.950400,0.049600
68227,PPI99446,10000,AKIA,Akiak,9/30/2014,Subrec Grants-PCE,331030,331030,15225003,3,...,2015-03-01,2014-09-01,9,2014,13303.94,88631,86684,84203,1.052600,-0.052600
68228,PPI99447,10000,FALSPE,False Pass,12/31/2014,Subrec Grants-PCE,331970,331970,15225003,6,...,2015-06-01,2014-12-01,12,2014,2592.43,51357,61067,57969,0.885900,0.114100
68229,PPI99614,10000,TDXA,Adak,11/30/2014,Subrec Grants-PCE,331005,331005,15225003,5,...,2015-05-01,2014-11-01,11,2014,17341.17,103979,162956,162956,0.638100,0.361900
68231,PPI99615,10000,KIPNLP,Kipnuk,12/31/2014,Subrec Grants-PCE,332080,332080,15225003,6,...,2015-06-01,2014-12-01,12,2014,15787.84,158364,170472,168382,0.940500,0.059500
68232,PPI99616,10000,KWIGPC,Kwigillingok,12/31/2014,Subrec Grants-PCE,332160,332160,15225003,6,...,2015-06-01,2014-12-01,12,2014,17653.57,126789,132950,128452,0.987100,0.012900
68233,PPI99617,10000,TDXM,Manley Hot Springs,11/30/2014,Subrec Grants-PCE,332200,332200,15225003,5,...,2015-05-01,2014-11-01,11,2014,11085.71,29663,37415,36152,0.820500,0.179500
68234,PPI99618,10000,NUNAIEC,Nunam Iqua,11/30/2014,Subrec Grants-PCE,332420,332420,15225003,5,...,2015-05-01,2014-11-01,11,2014,7255.38,82641,88327,86441,0.956000,0.044000
68236,PPI99619,10000,TUNTCSA,Tuntutuliak,12/31/2014,Subrec Grants-PCE,332720,332720,15225003,6,...,2015-06-01,2014-12-01,12,2014,13173.22,90151,104935,101182,0.891000,0.109000
68237,PPI99620,10000,AKIA,Akiak,7/31/2014,Subrec Grants-PCE,331030,331030,15225003,1,...,2015-01-01,2014-07-01,7,2014,13864.76,93915,77700,75656,1.241300,-0.241300
68238,PPI99621,10000,GOLOPU,Golovin,12/31/2014,Subrec Grants-PCE,332000,332000,15225003,6,...,2015-06-01,2014-12-01,12,2014,10723.77,77116,78217,78217,0.985900,0.014100
68239,PPI99622,10000,KINGC,King Cove,11/30/2014,Subrec Grants-PCE,332070,332070,15225003,5,...,2015-05-01,2014-11-01,11,2014,8065.82,317012,386000,377262,0.840300,0.159700
68240,PPI99623,10000,NEWKVC,Koliganek,12/31/2014,Subrec Grants-PCE,332110,332110,15225003,6,...,2015-06-01,2014-12-01,12,2014,9883.47,61041,67800,65033,0.938600,0.061400
68241,PPI99624,10000,TENAS,Tenakee Springs,12/31/2014,Subrec Grants-PCE,332630,332630,15225003,6,...,2015-06-01,2014-12-01,12,2014,8412.19,30928,36657,35522,0.870700,0.129300
68242,PPI99681,10000,INSIPEC,Angoon,1/31/2015,Subrec Grants-PCE,332650,332650,15225003,7,...,2015-07-01,2015-01-01,1,2015,29728.32,144770,168282,161776,0.894900,0.105100
68243,PPI99682,10000,INSIPEC,Chilkat Valley,1/31/2015,Subrec Grants-PCE,332660,332660,15225003,7,...,2015-07-01,2015-01-01,1,2015,18412.64,104287,163140,154253,0.676100,0.323900
68244,PPI99683,10000,INSIPEC,Hoonah,1/31/2015,Subrec Grants-PCE,332670,332670,15225003,7,...,2015-07-01,2015-01-01,1,2015,69778.06,377677,417604,409701,0.921800,0.078200
68245,PPI99684,10000,INSIPEC,Kake,1/31/2015,Subrec Grants-PCE,332680,332680,15225003,7,...,2015-07-01,2015-01-01,1,2015,38422.31,192747,220955,213955,0.900900,0.099100
68246,PPI99685,10000,INSIPEC,Klukwan,1/31/2015,Subrec Grants-PCE,332700,332700,15225003,7,...,2015-07-01,2015-01-01,1,2015,8314.23,35540,0,0,inf,-inf
68247,PPI99686,10000,INSIPEC,Angoon,2/28/2015,Subrec Grants-PCE,332650,332650,15225003,8,...,2015-08-01,2015-02-01,2,2015,28413.57,140223,159846,154308,0.908700,0.091300
68248,PPI99687,10000,INSIPEC,Chilkat Valley,2/28/2015,Subrec Grants-PCE,332660,332660,15225003,8,...,2015-08-01,2015-02-01,2,2015,17249.18,98027,157380,152891,0.641200,0.358800
68249,PPI99688,10000,INSIPEC,Hoonah,2/28/2015,Subrec Grants-PCE,332670,332670,15225003,8,...,2015-08-01,2015-02-01,2,2015,69085.21,363081,395018,387856,0.936100,0.063900
68250,PPI99689,10000,INSIPEC,Kake,2/28/2015,Subrec Grants-PCE,332680,332680,15225003,8,...,2015-08-01,2015-02-01,2,2015,35501.95,178512,206657,200157,0.891900,0.108100
68251,PPI99690,10000,INSIPEC,Klukwan,2/28/2015,Subrec Grants-PCE,332700,332700,15225003,8,...,2015-08-01,2015-02-01,2,2015,7937.97,33872,0,0,inf,-inf
68252,PPI99691,10000,BUCK,Buckland,1/31/2015,Subrec Grants-PCE,331820,331820,15225003,7,...,2015-07-01,2015-01-01,1,2015,11375.81,159909,175636,172833,0.925200,0.074800
68253,PPI99692,10000,KOTZEA,Kotzebue,1/31/2015,Subrec Grants-PCE,332130,332130,15225003,7,...,2015-07-01,2015-01-01,1,2015,113869.30,1810611,1948708,1914185,0.945900,0.054100

In [102]:
pce['Year_Intertied'] = pce['Year_Intertied'].astype('str')

In [103]:
pce = pce[pce['Year_Intertied'] != 'Northway Junction']

In [104]:
pce['Year_Intertied'] = pce['Year_Intertied'].astype('datetime64[ns]')

C:\Users\AEAData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [105]:
pce.shape

(35088, 94)

In [106]:
line_loss = ['Community_Name', 'Year_Intertied','Calendar_Date', 'Total_Sold', 'Total_Generated', 'Total_Adjusted_Generation', 
             'Line_Loss', 'Year', 'receiving_intertied_power']

In [107]:
sh(pce[line_loss].query("Total_Generated <= 0 and receiving_intertied_power == 'Yes' and Calendar_Date > Year_Intertied"), show_toolbar=True)

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': True, 'defauâ€¦

In [108]:
pce.shape

(35088, 94)

In [109]:
pce.query("~(Total_Generated <= 0 and receiving_intertied_power == 'Yes' and Calendar_Date > Year_Intertied)").shape

(32926, 94)

In [110]:
pce=pce.query("~(Total_Generated <= 0 and receiving_intertied_power == 'Yes' and Calendar_Date > Year_Intertied)")
pce.shape

(32926, 94)

In [111]:
line_nas = pce.query("Line_Loss != Line_Loss")
line_nas

,Document No.,Line_No,Buy_from_Vendor_No.,Community_Name,Posting_Date,Posting_Description,Project_Code,Column1,Shortcut_Dimension_4_Code,Stage_Code,...,Fiscal_Date,Calendar_Date,Month,Year,Amount_Combined,Total_Sold,Total_Generated,Total_Adjusted_Generation,Line_Efficiency,Line_Loss
0,NaN,10000,NORTSB,Nuiqsut,12/31/2009,Subrec Grants-PCE,332380,332380,10225003,2,...,2010-02-01,2009-08-01,8,2009,1036.68,0,0,0,NaN,NaN
11492,HISTPI035698,10000,PORTHU,Port Heiden,4/4/2008,Subrec Grants-PCE,332500,332500,5225003,1,...,2005-01-01,2004-07-01,7,2004,808.81,0,0,0,NaN,NaN
18519,HISTPI039146,10000,BEAVJU,Beaver,4/7/2008,Subrec Grants-PCE,331790,331790,4225003,1,...,2004-01-01,2003-07-01,7,2003,1846.37,0,0,0,NaN,NaN
18520,HISTPI039147,10000,BEAVJU,Beaver,4/7/2008,Subrec Grants-PCE,331790,331790,4225003,2,...,2004-02-01,2003-08-01,8,2003,2291.13,0,0,0,NaN,NaN
18521,HISTPI039148,10000,BEAVJU,Beaver,4/7/2008,Subrec Grants-PCE,331790,331790,4225003,3,...,2004-03-01,2003-09-01,9,2003,3038.94,0,0,0,NaN,NaN
18522,HISTPI039149,10000,BEAVJU,Beaver,4/7/2008,Subrec Grants-PCE,331790,331790,4225003,6,...,2004-06-01,2003-12-01,12,2003,1808.57,0,0,0,NaN,NaN
18523,HISTPI039150,10000,BEAVJU,Beaver,4/7/2008,Subrec Grants-PCE,331790,331790,4225003,7,...,2004-07-01,2004-01-01,1,2004,1685.09,0,0,0,NaN,NaN
18524,HISTPI039151,10000,BEAVJU,Beaver,4/7/2008,Subrec Grants-PCE,331790,331790,4225003,9,...,2004-09-01,2004-03-01,3,2004,3094.61,0,0,0,NaN,NaN
18525,HISTPI039152,10000,BEAVJU,Beaver,4/7/2008,Subrec Grants-PCE,331790,331790,4225003,10,...,2004-10-01,2004-04-01,4,2004,1223.14,0,0,0,NaN,NaN
18526,HISTPI039153,10000,BEAVJU,Beaver,4/7/2008,Subrec Grants-PCE,331790,331790,4225003,11,...,2004-11-01,2004-05-01,5,2004,1269.26,0,0,0,NaN,NaN
22451,HISTPI041175,10000,PILOPEU,Pilot Point,4/7/2008,Subrec Grants-PCE,332480,332480,3225003,5,...,2003-05-01,2002-11-01,11,2002,0.00,0,0,0,NaN,NaN
24833,HISTPI042298,10000,PORTHU,Port Heiden,4/9/2008,Subrec Grants-PCE,332500,332500,2225003,2,...,2002-02-01,2001-08-01,8,2001,299.48,0,0,0,NaN,NaN
24834,HISTPI042299,10000,PORTHU,Port Heiden,4/9/2008,Subrec Grants-PCE,332500,332500,2225003,3,...,2002-03-01,2001-09-01,9,2001,166.13,0,0,0,NaN,NaN
24835,HISTPI042300,10000,PORTHU,Port Heiden,4/9/2008,Subrec Grants-PCE,332500,332500,2225003,4,...,2002-04-01,2001-10-01,10,2001,166.13,0,0,0,NaN,NaN
24836,HISTPI042301,10000,PORTHU,Port Heiden,4/9/2008,Subrec Grants-PCE,332500,332500,2225003,5,...,2002-05-01,2001-11-01,11,2001,166.13,0,0,0,NaN,NaN
24837,HISTPI042302,10000,PORTHU,Port Heiden,4/9/2008,Subrec Grants-PCE,332500,332500,2225003,6,...,2002-06-01,2001-12-01,12,2001,174.57,0,0,0,NaN,NaN
41695,PPI45462,10000,UNGUPC,Newtok,10/7/2008,Subrec Grants-PCE,332870,332870,8225003,9,...,2008-09-01,2008-03-01,3,2008,9136.53,0,0,0,NaN,NaN

In [112]:
pce.query

<bound method DataFrame.query of        Document No.  Line_No Buy_from_Vendor_No.      Community_Name  \
0               NaN    10000              NORTSB             Nuiqsut
1      HISTPI030007    10000             ANIALPC               Aniak
2      HISTPI030008    10000              BETHUC              Bethel
6      HISTPI030009    10000             INSIPEC      Chilkat Valley
7      HISTPI030010    10000              TANAPC              Tanana
8      HISTPI030011    10000             INSIPEC              Angoon
9      HISTPI030012    10000             INSIPEC              Hoonah
12     HISTPI030013    10000             INSIPEC                Kake
14     HISTPI030015    10000             ALASPCA        Coffman Cove
16     HISTPI030016    10000             ALASPCA        Coffman Cove
18     HISTPI030017    10000             ALASPCA               Craig
21     HISTPI030018    10000             ALASPCA              Haines
28     HISTPI030022    10000             ALASPCA         Naukati Bay
30     HISTPI030023    10000             ALASPCA         Naukati Bay
32     HISTPI030024    10000             ALASPCA             Skagway
36     HISTPI030026    10000             ALASPCA          Whale Pass
39     HISTPI030027    10000             ALASPCA          Whale Pass
40     HISTPI030028    10000              CENTEI             Central
42     HISTPI030029    10000               MANLU  Manley Hot Springs
45     HISTPI030030    10000              TANAEC       Port Alsworth
47     HISTPI030031    10000             UNALVEC          Unalakleet
49     HISTPI030032    10000             ILIANNE             Iliamna
52     HISTPI030033    10000              MCGRLP             McGrath
54     HISTPI030034    10000              NATELP           Chefornak
55     HISTPI030035    10000              WHITMU      White Mountain
57     HISTPI030036    10000              NAKNEA              Naknek
61     HISTPI030036    50000              NAKNEA              Naknek
62     HISTPI030037    10000               UMNAP            Nikolski
63     HISTPI030038    10000             ALASPCA           Allakaket
64     HISTPI030039    10000             ALASPCA             Bettles
...             ...      ...                 ...                 ...
68219      PPI99422    10000             MIDDKEC       Crooked Creek
68220      PPI99423    10000             MIDDKEC           Red Devil
68221      PPI99424    10000             MIDDKEC           Sleetmute
68222      PPI99425    10000             MIDDKEC         Stony River
68223      PPI99426    10000             LARSBUC          Larsen Bay
68224      PPI99440    10000               YAKUP             Yakutat
68226      PPI99441    10000               CHITE             Chitina
68227      PPI99446    10000                AKIA               Akiak
68228      PPI99447    10000              FALSPE          False Pass
68229      PPI99614    10000                TDXA                Adak
68231      PPI99615    10000              KIPNLP              Kipnuk
68232      PPI99616    10000              KWIGPC        Kwigillingok
68233      PPI99617    10000                TDXM  Manley Hot Springs
68234      PPI99618    10000             NUNAIEC          Nunam Iqua
68236      PPI99619    10000             TUNTCSA         Tuntutuliak
68237      PPI99620    10000                AKIA               Akiak
68238      PPI99621    10000              GOLOPU             Golovin
68239      PPI99622    10000               KINGC           King Cove
68240      PPI99623    10000              NEWKVC           Koliganek
68241      PPI99624    10000               TENAS     Tenakee Springs
68242      PPI99681    10000             INSIPEC              Angoon
68243      PPI99682    10000             INSIPEC      Chilkat Valley
68244      PPI99683    10000             INSIPEC              Hoonah
68245      PPI99684    10000             INSIPEC                Kake
68247      PPI99686    10000             INSIPEC              Angoon
68248      PPI99687    10000             INSIPEC      Chilkat Valley
68249      PPI99688    10000             INSIPEC              Hoonah
68250      PPI99689    10000             INSIPEC                Kake
68252      PPI99691    10000                BUCK            Buckland
68253      PPI99692    10000              KOTZEA            Kotzebue

      Posting_Date Posting_Description  Project_Code  Column1  \
0       12/31/2009   Subrec Grants-PCE        332380   332380
1         4/3/2008   Subrec Grants-PCE        331760   331760
2         4/3/2008   Subrec Grants-PCE        331800   331800
6         4/3/2008   Subrec Grants-PCE        332660   332660
7         4/3/2008   Subrec Grants-PCE        332600   332600
8         4/3/2008   Subrec Grants-PCE        332650   332650
9         4/3/2008   Subrec Grants-PCE        332670   332670
12        4/3/2008   Subrec Grants-PCE        332680   332680
14        4/3/2008   Subrec Grants-PCE        331080   331080
16        4/3/2008   Subrec Grants-PCE        331080   331080
18        4/3/2008   Subrec Grants-PCE        331090   331090
21        4/3/2008   Subrec Grants-PCE        331120   331120
28        4/3/2008   Subrec Grants-PCE        331170   331170
30        4/3/2008   Subrec Grants-PCE        331170   331170
32        4/3/2008   Subrec Grants-PCE        331190   331190
36        4/3/2008   Subrec Grants-PCE        331230   331230
39        4/3/2008   Subrec Grants-PCE        331230   331230
40        4/3/2008   Subrec Grants-PCE        331830   331830
42        4/3/2008   Subrec Grants-PCE        332200   332200
45        4/3/2008   Subrec Grants-PCE        332590   332590
47        4/3/2008   Subrec Grants-PCE        332850   332850
49        4/3/2008   Subrec Grants-PCE        332050   332050
52        4/3/2008   Subrec Grants-PCE        332220   332220
54        4/3/2008   Subrec Grants-PCE        332310   332310
55        4/3/2008   Subrec Grants-PCE        332890   332890
57        4/3/2008   Subrec Grants-PCE        332280   332280
61        4/3/2008   Subrec Grants-PCE        332280   332280
62        4/3/2008   Subrec Grants-PCE        332740   332740
63        4/3/2008   Subrec Grants-PCE        331050   331050
64        4/3/2008   Subrec Grants-PCE        331060   331060
...            ...                 ...           ...      ...
68219   12/31/2014   Subrec Grants-PCE        332240   332240
68220   12/31/2014   Subrec Grants-PCE        332250   332250
68221   12/31/2014   Subrec Grants-PCE        332260   332260
68222   12/31/2014   Subrec Grants-PCE        332270   332270
68223   12/31/2014   Subrec Grants-PCE        332170   332170
68224   12/31/2014   Subrec Grants-PCE        332900   332900
68226   12/31/2014   Subrec Grants-PCE        331890   331890
68227    9/30/2014   Subrec Grants-PCE        331030   331030
68228   12/31/2014   Subrec Grants-PCE        331970   331970
68229   11/30/2014   Subrec Grants-PCE        331005   331005
68231   12/31/2014   Subrec Grants-PCE        332080   332080
68232   12/31/2014   Subrec Grants-PCE        332160   332160
68233   11/30/2014   Subrec Grants-PCE        332200   332200
68234   11/30/2014   Subrec Grants-PCE        332420   332420
68236   12/31/2014   Subrec Grants-PCE        332720   332720
68237    7/31/2014   Subrec Grants-PCE        331030   331030
68238   12/31/2014   Subrec Grants-PCE        332000   332000
68239   11/30/2014   Subrec Grants-PCE        332070   332070
68240   12/31/2014   Subrec Grants-PCE        332110   332110
68241   12/31/2014   Subrec Grants-PCE        332630   332630
68242    1/31/2015   Subrec Grants-PCE        332650   332650
68243    1/31/2015   Subrec Grants-PCE        332660   332660
68244    1/31/2015   Subrec Grants-PCE        332670   332670
68245    1/31/2015   Subrec Grants-PCE        332680   332680
68247    2/28/2015   Subrec Grants-PCE        332650   332650
68248    2/28/2015   Subrec Grants-PCE        332660   332660
68249    2/28/2015   Subrec Grants-PCE        332670   332670
68250    2/28/2015   Subrec Grants-PCE        332680   332680
68252    1/31/2015   Subrec Grants-PCE        331820   331820
68253    1/31/2015   Subrec Grants-PCE        332130   332130

       Shortcut_Dimension_4_Code  Stage_Code    ...      Fiscal_Date  \
0                       10225003           2    ...       2010-02-01
1                        8225003           1    ...       2008-01-01
2                        8225003           1    ...       2008-01-01
6                        8225003           1    ...       2008-01-01
7                        8225003           1    ...       2008-01-01
8                        8225003           1    ...       2008-01-01
9                        8225003           1    ...       2008-01-01
12                       8225003           1    ...       2008-01-01
14                       8225003           1    ...       2008-01-01
16                       8225003           2    ...       2008-02-01
18                       8225003           1    ...       2008-01-01
21                       8225003           1    ...       2008-01-01
28                       8225003           1    ...       2008-01-01
30                       8225003           2    ...       2008-02-01
32                       8225003           1    ...       2008-01-01
36                       8225003           1    ...       2008-01-01
39                       8225003           2    ...       2008-02-01
40                       8225003           1    ...       2008-01-01
42                       8225003           1    ...       2008-01-01
45                       8225003           1    ...       2008-01-01
47                       8225003           1    ...       2008-01-01
49                       8225003           1    ...       2008-01-01
52                       8225003           1    ...       2008-01-01
54                       8225003           1    ...       2008-01-01
55                       8225003           1    ...       2008-01-01
57                       8225003           1    ...       2008-01-01
61                       8225003           1    ...       2008-01-01
62                       8225003           1    ...       2008-01-01
63                       8225003           1    ...       2008-01-01
64                       8225003           1    ...       2008-01-01
...                          ...         ...    ...              ...
68219                   15225003           6    ...       2015-06-01
68220                   15225003           6    ...       2015-06-01
68221                   15225003           6    ...       2015-06-01
68222                   15225003           6    ...       2015-06-01
68223                   15225003           6    ...       2015-06-01
68224                   15225003           6    ...       2015-06-01
68226                   15225003           6    ...       2015-06-01
68227                   15225003           3    ...       2015-03-01
68228                   15225003           6    ...       2015-06-01
68229                   15225003           5    ...       2015-05-01
68231                   15225003           6    ...       2015-06-01
68232                   15225003           6    ...       2015-06-01
68233                   15225003           5    ...       2015-05-01
68234                   15225003           5    ...       2015-05-01
68236                   15225003           6    ...       2015-06-01
68237                   15225003           1    ...       2015-01-01
68238                   15225003           6    ...       2015-06-01
68239                   15225003           5    ...       2015-05-01
68240                   15225003           6    ...       2015-06-01
68241                   15225003           6    ...       2015-06-01
68242                   15225003           7    ...       2015-07-01
68243                   15225003           7    ...       2015-07-01
68244                   15225003           7    ...       2015-07-01
68245                   15225003           7    ...       2015-07-01
68247                   15225003           8    ...       2015-08-01
68248                   15225003           8    ...       2015-08-01
68249                   15225003           8    ...       2015-08-01
68250                   15225003           8    ...       2015-08-01
68252                   15225003           7    ...       2015-07-01
68253                   15225003           7    ...       2015-07-01

      Calendar_Date Month  Year  Amount_Combined  Total_Sold  Total_Generated  \
0        2009-08-01     8  2009          1036.68           0                0
1        2007-07-01     7  2007         20443.57      150461           173900
2        2007-07-01     7  2007        147731.51     2943211          3267200
6        2007-07-01     7  2007         11334.80       88931           141000
7        2007-07-01     7  2007          9755.49       69592            80220
8        2007-07-01     7  2007         17886.25      125485           147565
9        2007-07-01     7  2007         45565.95      408286           460722
12       2007-07-01     7  2007         21851.38      155140           184987
14       2007-07-01     7  2007          9227.04       74644            82715
16       2007-08-01     8  2007          9702.37       84766            89226
18       2007-07-01     7  2007         12020.66      960639          2259321
21       2007-07-01     7  2007         20646.69      973797          1115565
28       2007-07-01     7  2007          5162.71       33753            36919
30       2007-08-01     8  2007          4887.14       34704            37606
32       2007-07-01     7  2007         15053.65     1383215          1476192
36       2007-07-01     7  2007          3743.81       33746            40320
39       2007-08-01     8  2007          3421.68       41011            43968
40       2007-07-01     7  2007          5785.44       32638            36279
42       2007-07-01     7  2007          2794.64       16169            21360
45       2007-07-01     7  2007          5521.25       53966            57835
47       2007-07-01     7  2007         19765.08      251129           266640
49       2007-07-01     7  2007         18141.95      209740           256300
52       2007-07-01     7  2007         17365.59      184383           211200
54       2007-07-01     7  2007          8748.65       56253            67038
55       2007-07-01     7  2007          7667.82       39315            45300
57       2007-07-01     7  2007         57679.48     3957515          3940165
61       2007-07-01     7  2007         57679.48     3957515          3940165
62       2007-07-01     7  2007          1807.00       19451            25536
63       2007-07-01     7  2007          6643.72       34993            37091
64       2007-07-01     7  2007          4085.02       33148            37284
...             ...   ...   ...              ...         ...              ...
68219    2014-12-01    12  2014          9273.43       22506            22801
68220    2014-12-01    12  2014          1904.05        3627             4882
68221    2014-12-01    12  2014          8084.72       19780            27350
68222    2014-12-01    12  2014          2111.20        8344            10057
68223    2014-12-01    12  2014           809.18       80775            96806
68224    2014-12-01    12  2014         37893.37      401201           444687
68226    2014-12-01    12  2014          3259.99       34970            40607
68227    2014-09-01     9  2014         13303.94       88631            86684
68228    2014-12-01    12  2014          2592.43       51357            61067
68229    2014-11-01    11  2014         17341.17      103979           162956
68231    2014-12-01    12  2014         15787.84      158364           170472
68232    2014-12-01    12  2014         17653.57      126789           132950
68233    2014-11-01    11  2014         11085.71       29663            37415
68234    2014-11-01    11  2014          7255.38       82641            88327
68236    2014-12-01    12  2014         13173.22       90151           104935
68237    2014-07-01     7  2014         13864.76       93915            77700
68238    2014-12-01    12  2014         10723.77       77116            78217
68239    2014-11-01    11  2014          8065.82      317012           386000
68240    2014-12-01    12  2014          9883.47       61041            67800
68241    2014-12-01    12  2014          8412.19       30928            36657
68242    2015-01-01     1  2015         29728.32      144770           168282
68243    2015-01-01     1  2015         18412.64      104287           163140
68244    2015-01-01     1  2015         69778.06      377677           417604
68245    2015-01-01     1  2015         38422.31      192747           220955
68247    2015-02-01     2  2015         28413.57      140223           159846
68248    2015-02-01     2  2015         17249.18       98027           157380
68249    2015-02-01     2  2015         69085.21      363081           395018
68250    2015-02-01     2  2015         35501.95      178512           206657
68252    2015-01-01     1  2015         11375.81      159909           175636
68253    2015-01-01     1  2015        113869.30     1810611          1948708

       Total_Adjusted_Generation  Line_Efficiency  Line_Loss
0                              0              NaN        NaN
1                         171390           0.8779     0.1221
2                        3209600           0.9170     0.0830
6                         135614           0.6558     0.3442
7                          77130           0.9023     0.0977
8                         145018           0.8653     0.1347
9                         453047           0.9012     0.0988
12                        177787           0.8726     0.1274
14                         82055           0.9097     0.0903
16                         88362           0.9593     0.0407
18                       2242111           0.4285     0.5715
21                       1092645           0.8912     0.1088
28                         35551           0.9494     0.0506
30                         36190           0.9589     0.0411
32                       1471753           0.9398     0.0602
36                         39653           0.8510     0.1490
39                         42582           0.9631     0.0369
40                         34923           0.9346     0.0654
42                         19901           0.8125     0.1875
45                         57070           0.9456     0.0544
47                        261106           0.9618     0.0382
49                        242020           0.8666     0.1334
52                        199455           0.9244     0.0756
54                         65693           0.8563     0.1437
55                         43246           0.9091     0.0909
57                       3854634           1.0267    -0.0267
61                       3854634           1.0267    -0.0267
62                         23761           0.8186     0.1814
63                         36765           0.9518     0.0482
64                         37215           0.8907     0.1093
...                          ...              ...        ...
68219                      22801           0.9871     0.0129
68220                       4806           0.7547     0.2453
68221                      26375           0.7500     0.2500
68222                       9359           0.8915     0.1085
68223                      94338           0.8562     0.1438
68224                     434629           0.9231     0.0769
68226                      36796           0.9504     0.0496
68227                      84203           1.0526    -0.0526
68228                      57969           0.8859     0.1141
68229                     162956           0.6381     0.3619
68231                     168382           0.9405     0.0595
68232                     128452           0.9871     0.0129

In [113]:
pce[line_loss].dropna(subset=['Line_Loss'], inplace=True)
sh(pce[line_loss], show_toolbar=True)

C:\Users\AEAData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': True, 'defauâ€¦

In [114]:
pce[line_loss].isnull().sum()

Community_Name                 282
Year_Intertied               30397
Calendar_Date                    0
Total_Sold                       0
Total_Generated                  0
Total_Adjusted_Generation        0
Line_Loss                       17
Year                             0
receiving_intertied_power      282
dtype: int64

In [115]:
pce[line_loss].query("Line_Loss == '-inf'")

,Community_Name,Year_Intertied,Calendar_Date,Total_Sold,Total_Generated,Total_Adjusted_Generation,Line_Loss,Year,receiving_intertied_power
135,Beaver,NaT,2007-07-01,27038,0,0,-inf,2007,No
311,Ruby,NaT,2007-07-01,27796,0,0,-inf,2007,No
322,Koliganek,NaT,2007-07-01,36624,0,0,-inf,2007,No
405,Beaver,NaT,2007-08-01,13752,0,0,-inf,2007,No
425,Ekwok,NaT,2007-07-01,33165,0,0,-inf,2007,No
452,Koliganek,NaT,2007-08-01,36374,0,0,-inf,2007,No
453,Ruby,NaT,2007-08-01,31041,0,0,-inf,2007,No
639,Ekwok,NaT,2007-08-01,34707,0,0,-inf,2007,No
722,Nelson Lagoon,NaT,2007-09-01,34501,0,0,-inf,2007,No
732,Nikolai,NaT,2007-07-01,17682,0,0,-inf,2007,No
733,Nikolai,NaT,2007-08-01,19000,0,0,-inf,2007,No
890,Ruby,NaT,2007-09-01,28236,0,0,-inf,2007,No
1022,Ruby,NaT,2007-10-01,38221,0,0,-inf,2007,No
1251,Ruby,NaT,2007-11-01,36706,0,0,-inf,2007,No
1289,Beaver,NaT,2007-09-01,11492,0,0,-inf,2007,No
1290,Beaver,NaT,2007-11-01,20917,0,0,-inf,2007,No
1318,Ekwok,NaT,2007-09-01,35509,0,0,-inf,2007,No
1320,Ekwok,NaT,2007-10-01,3521,0,0,-inf,2007,No
1322,Ekwok,NaT,2007-11-01,58040,0,0,-inf,2007,No
1344,Koliganek,NaT,2007-09-01,35869,0,0,-inf,2007,No
1605,Larsen Bay,NaT,2007-11-01,56799,0,0,-inf,2007,No
1643,Ruby,NaT,2007-12-01,57853,0,0,-inf,2007,No
1646,Koliganek,NaT,2007-10-01,44321,0,0,-inf,2007,No
1647,Koliganek,NaT,2007-11-01,48009,0,0,-inf,2007,No
1682,Koliganek,NaT,2007-12-01,42974,0,0,-inf,2007,No
1866,Ruby,NaT,2008-01-01,50564,0,0,-inf,2008,No
1912,Beaver,NaT,2007-10-01,20137,0,0,-inf,2007,No
1913,Beaver,NaT,2007-12-01,18873,0,0,-inf,2007,No
1914,Beaver,NaT,2008-01-01,24781,0,0,-inf,2008,No
2222,Ekwok,NaT,2007-12-01,34373,0,0,-inf,2007,No
...,...,...,...,...,...,...,...,...,...
63080,Deering,NaT,2013-07-01,36889,0,0,-inf,2013,No
63083,Deering,NaT,2013-08-01,45707,0,0,-inf,2013,No
63085,Deering,NaT,2013-09-01,51782,0,0,-inf,2013,No
64204,Hughes,NaT,2013-12-01,31215,0,0,-inf,2013,No
64480,Takotna,NaT,2014-01-01,18904,0,0,-inf,2014,No
65354,Takotna,NaT,2014-02-01,16558,0,0,-inf,2014,No
65355,Takotna,NaT,2014-03-01,19384,0,0,-inf,2014,No
65940,Dot Lake,NaT,2014-05-01,27536,0,0,-inf,2014,Yes
65961,Crooked Creek,NaT,2014-05-01,15881,0,0,-inf,2014,No
65977,Point Hope,NaT,2014-05-01,488839,0,0,-inf,2014,No
65997,Crooked Creek,NaT,2014-06-01,13602,0,0,-inf,2014,No
66044,Dot Lake,NaT,2014-06-01,18860,0,0,-inf,2014,Yes
66271,Point Hope,NaT,2014-06-01,314603,0,0,-inf,2014,No
66404,Dot Lake,NaT,2014-07-01,24292,0,0,-inf,2014,Yes
66642,Beaver,NaT,2014-08-01,21223,0,0,-inf,2014,No
66894,Dot Lake,NaT,2014-08-01,23444,0,0,-inf,2014,Yes
66958,Point Hope,NaT,2014-08-01,446975,0,0,-inf,2014,No
66961,Point Hope,NaT,2014-07-01,453342,0,0,-inf,2014,No
67029,Takotna,NaT,2014-08-01,10835,0,0,-inf,2014,No
67043,Dot Lake,NaT,2014-09-01,27113,0,0,-inf,2014,Yes
67085,Tatitlek,NaT,2014-09-01,20350,0,0,-inf,2014,No
67288,Point Hope,NaT,2014-09-01,428466,0,0,-inf,2014,No
67340,Dot Lake,NaT,2014-10-01,35590,0,0,-inf,2014,Yes
67655,Dot Lake,NaT,2014-11-01,29542,0,0,-inf,2014,Yes
67863,Point Hope,NaT,2014-10-01,476426,0,0,-inf,2014,No
67873,Arctic Village,NaT,2014-11-01,30041,0,0,-inf,2014,No
67976,Tatitlek,NaT,2014-10-01,46719,0,0,-inf,2014,No
67978,Tatitlek,NaT,2014-11-01,37365,0,0,-inf,2014,No
67984,Dot Lake,NaT,2014-12-01,38715,0,0,-inf,2014,Yes
68007,Arctic Village,NaT,2014-12-01,30160,0,0,-inf,2014,No

In [121]:
#query number of records where more kWh was sold than generated
pce_IS =pce[line_loss].query("Total_Sold > Total_Generated")

In [122]:
#sort resulting records by community name and date, and report unique community records by community name
pce_IS_Filter =pce_IS.sort_values(['Community_Name', 'Calendar_Date'])
pce_IS_Filter.Community_Name.unique()

array(['Adak', 'Akhiok', 'Akiachak', 'Akiak', 'Akutan', 'Alakanuk',
       'Allakaket', 'Ambler', 'Anaktuvuk Pass', 'Angoon', 'Aniak',
       'Anvik', 'Arctic Village', 'Atka', 'Atmautluak', 'Atqasuk',
       'Beaver', 'Bethel', 'Bettles', 'Brevig Mission', 'Buckland',
       'Central', 'Chalkyitsik', 'Chefornak', 'Chenega Bay', 'Chevak',
       'Chignik', 'Chignik Lagoon', 'Chignik Lake', 'Chilkat Valley',
       'Chistochina', 'Chuathbaluk', 'Coffman Cove', 'Cold Bay',
       'Cordova', 'Crooked Creek', 'Deering', 'Dillingham', 'Diomede',
       'Dot Lake', 'Eagle', 'Eek', 'Egegik', 'Ekwok', 'Elfin Cove',
       'Elim', 'Emmonak', 'False Pass', 'Fort Yukon', 'Galena', 'Gambell',
       'Golovin', 'Goodnews Bay', 'Grayling', 'Gustavus', 'Haines',
       'Healy Lake', 'Hollis', 'Holy Cross', 'Hoonah', 'Hooper Bay',
       'Hughes', 'Huslia', 'Hydaburg', 'Igiugig', 'Iliamna', 'Kaktovik',
       'Kalskag', 'Kaltag', 'Karluk', 'Kasigluk', 'Kiana', 'King Cove',
       'Kipnuk', 'Kivalina', 'Kobuk', 'Kokhanok', 'Koliganek',
       'Kongiganak', 'Kotlik', 'Kotzebue', 'Koyuk', 'Koyukuk', 'Kwethluk',
       'Kwigillingok', 'Larsen Bay', 'Levelock', 'Lime Village',
       'Lower Kalskag', 'Manokotak', 'Marshall', 'McGrath', 'Mekoryuk',
       'Mentasta Lake', 'Minto', 'Mountain Village', 'Naknek', 'Napakiak',
       'Napaskiak', 'Naukati Bay', 'Nelson Lagoon', 'New Stuyahok',
       'Newtok', 'Nightmute', 'Nikolai', 'Nikolski', 'Noatak', 'Nome',
       'Noorvik', 'Northway', 'Nuiqsut', 'Nulato', 'Nunam Iqua',
       'Nunapitchuk', 'Old Harbor', 'Ouzinkie', 'Pedro Bay', 'Pelican',
       'Perryville', 'Pilot Station', 'Platinum', 'Point Hope',
       'Point Lay', 'Port Heiden', 'Quinhagak', 'Red Devil', 'Ruby',
       'Russian Mission', 'Saint George', "Saint Mary's", 'Saint Michael',
       'Saint Paul', 'Sand Point', 'Savoonga', 'Scammon Bay', 'Selawik',
       'Shageluk', 'Shaktoolik', 'Shishmaref', 'Shungnak', 'Skagway',
       'Sleetmute', 'Stebbins', 'Stevens Village', 'Stony River',
       'Takotna', 'Tanana', 'Tatitlek', 'Teller', 'Tenakee Springs',
       'Tetlin', 'Thorne Bay', 'Togiak', 'Toksook Bay', 'Tuluksak',
       'Tuntutuliak', 'Tununak', 'Twin Hills', 'Unalaska', 'Venetie',
       'Wainwright', 'Wales', 'White Mountain', 'Yakutat', nan],
      dtype=object)

In [124]:
#can be modified to extend number of rows displayed by adding none after 'diplay.max_rows',
pd.reset_option('display.max_rows',) 
pd.set_option('display.max_columns', None)
sh(pce_IS_Filter, show_toolbar=True)

QgridWidget(grid_options={'fullWidthRows': True, 'syncColumnCellResize': True, 'forceFitColumns': True, 'defauâ€¦

In [125]:
# times community had more kwh sold than produced
pce_IS_Filter['Community_Name'].value_counts()

Dot Lake           203
Manokotak           96
Beaver              83
Ruby                83
Ekwok               74
Port Heiden         71
Twin Hills          63
Hughes              62
Nikolai             59
Kasigluk            57
Kaktovik            56
Atmautluak          54
Larsen Bay          50
Akiak               45
Kalskag             43
Alakanuk            41
Koliganek           40
Scammon Bay         40
Hooper Bay          35
Deering             35
Kongiganak          32
Huslia              31
Chignik Lagoon      31
Selawik             30
Napaskiak           29
Pilot Station       28
Diomede             27
Levelock            27
Nelson Lagoon       26
Noorvik             26
                  ...
Hydaburg             3
Iliamna              3
Northway             3
Venetie              3
Platinum             3
Healy Lake           3
Red Devil            3
Ouzinkie             2
Anaktuvuk Pass       2
Pelican              2
Cold Bay             2
Hollis               2
Wainwright           2
Dillingham           2
Tenakee Springs      2
Bettles              2
Angoon               1
Saint Paul           1
Thorne Bay           1
Pedro Bay            1
Chilkat Valley       1
Gustavus             1
Haines               1
Tetlin               1
McGrath              1
Tanana               1
Eagle                1
Hoonah               1
Lower Kalskag        1
Aniak                1
Name: Community_Name, Length: 164, dtype: int64

In [126]:
# frequency of date that a community sold more kWh than produced
pce_IS_Filter['Calendar_Date'].value_counts()

2016-08-01    51
2011-04-01    39
2004-08-01    26
2004-09-01    26
2001-09-01    25
2002-06-01    25
2002-01-01    25
2003-12-01    23
2007-06-01    23
2008-08-01    23
2004-10-01    23
2007-05-01    23
2005-04-01    23
2002-03-01    22
2001-11-01    22
2004-06-01    22
2008-02-01    22
2002-04-01    22
2004-12-01    22
2006-01-01    22
2006-02-01    22
2005-02-01    22
2002-08-01    22
2004-07-01    22
2003-10-01    22
2001-10-01    21
2002-02-01    21
2005-06-01    21
2009-02-01    21
2010-08-01    21
              ..
2015-05-01     9
2015-08-01     9
2018-05-01     8
2017-03-01     8
2017-06-01     8
2003-03-01     8
2014-07-01     8
2017-11-01     8
2016-03-01     8
2016-09-01     8
2011-02-01     8
2018-02-01     7
2016-10-01     7
2013-09-01     7
2016-01-01     7
2016-05-01     7
2017-07-01     7
2013-11-01     7
2011-08-01     7
2017-01-01     7
2013-05-01     7
2017-02-01     6
2018-06-01     6
2015-09-01     6
2015-07-01     6
2016-07-01     5
2011-07-01     5
2016-04-01     5
2016-11-01     5
2016-06-01     4
Name: Calendar_Date, Length: 204, dtype: int64

In [127]:
# frequency by year of more kWh sold than produced
pce_IS_Filter['Year'].value_counts()

2004    246
2002    235
2005    228
2006    208
2008    202
2007    194
2009    190
2003    186
2010    165
2011    158
2014    149
2012    143
2001    126
2016    125
2013    122
2015    120
2017    108
2018     57
Name: Year, dtype: int64